<a href="https://colab.research.google.com/github/L-Hyunwoo/Machine-Learning/blob/main/%5B7_1%5DLearning_Rate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Lab 7 Learning rate and Evaluation
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))


Instructions for updating:
non-resource variables are not supported in the long term
0 1.1558543 [[ 0.5807229   0.53629667  0.28503624]
 [-0.880366   -0.5175341  -0.27097937]
 [ 1.1865109   0.58328104 -0.3828085 ]]
1 1.0075483 [[ 0.5547206   0.5424017   0.30493358]
 [-0.9547444  -0.49127546 -0.22285959]
 [ 1.0872434   0.63115525 -0.3314152 ]]
2 0.92436826 [[ 0.5528882   0.5286323   0.3205353 ]
 [-0.90297264 -0.5720706  -0.19383623]
 [ 1.1160883   0.56790024 -0.2970051 ]]
3 0.89032674 [[ 0.53469634  0.53762937  0.3297301 ]
 [-0.9394094  -0.5328238  -0.19664629]
 [ 1.0536007   0.62223166 -0.28884894]]
4 0.87250215 [[ 0.5328474   0.52988255  0.33932585]
 [-0.89041984 -0.58170545 -0.19675417]
 [ 1.0803318   0.58640695 -0.27975532]]
5 0.8590492 [[ 0.51894367  0.53647655  0.34663558]
 [-0.90588945 -0.55437213 -0.20861787]
 [ 1.0402896   0.62676066 -0.28006688]]
6 0.8482194 [[ 0.5151779   0.5313864   0.35549155]
 [-0.86864805 -0.58820254 -0.21202885]
 [ 1.0560089   0.6048408  -0.27386636]]
7 