<a href="https://colab.research.google.com/github/L-Hyunwoo/Machine-Learning/blob/main/%5B7_1%5DLearning_Rate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# Lab 7 Learning rate and Evaluation
import tensorflow as tf

#Use tensorflow1.0 codes in a tensorflow2.0 environment
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

tf.set_random_seed(777)  # for reproducibility

In [9]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

In [10]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [11]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 5.2386894 [[-1.0658652  -0.6447904  -1.8930764 ]
 [ 0.17781954 -1.0100104   1.0449628 ]
 [ 0.31796053  0.8274616  -0.75732005]]
1 2.8903503 [[-1.1271603  -0.60892534 -1.8676463 ]
 [-0.04114614 -0.83879876  1.0927168 ]
 [ 0.09000733  1.0076561  -0.70956135]]
2 1.767929 [[-1.1389573  -0.5860959  -1.8786788 ]
 [-0.02013839 -0.7074682   0.94037855]
 [ 0.10476907  1.1242691  -0.8409361 ]]
3 1.3721359 [[-1.1597569  -0.5814066  -1.8625685 ]
 [-0.05559054 -0.66973335  0.93809587]
 [ 0.07984807  1.1409535  -0.8326995 ]]
4 1.35323 [[-1.1699781  -0.5849816  -1.8487722 ]
 [-0.03695338 -0.6751287   0.92485404]
 [ 0.1082859   1.11233    -0.83251375]]
5 1.3375983 [[-1.1866217  -0.58328754 -1.8338227 ]
 [-0.0517488  -0.6533923   0.9179131 ]
 [ 0.10314833  1.1126286  -0.8276748 ]]
6 1.3244691 [[-1.1991038  -0.5848864  -1.8197417 ]
 [-0.04558229 -0.6489834   0.9073377 ]
 [ 0.11855166  1.0949404  -0.82539   ]]
7 1.3121096 [[-1.2140872  -0.58435744 -1.8052871 ]
 [-0.05271307 -0.633749    0.89923406]
 [ 