<a href="https://colab.research.google.com/github/L-Hyunwoo/Machine-Learning/blob/main/%5B7_2%5Dlinear_regression_min_max_scale.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

#Use tensorflow1.0 codes in a tensorflow2.0 environment
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

tf.set_random_seed(777)  # for reproducibility

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [4]:
xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

In [ ]:
# very important. It does not work without it.
xy = min_max_scaler(xy)
print(xy)

In [6]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [7]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [8]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

In [9]:
# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())

    for step in range(101):
        _, cost_val, hy_val = sess.run(
            [train, cost, hypothesis], feed_dict={X: x_data, Y: y_data}
        )
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  2.2966743 
Prediction:
 [[-0.90906316]
 [-0.72825223]
 [-0.941653  ]
 [-1.1535423 ]
 [-1.0526859 ]
 [-0.9654564 ]
 [-1.2137954 ]
 [-0.95066893]]
1 Cost:  2.2965026 
Prediction:
 [[-0.9089874]
 [-0.728179 ]
 [-0.9415915]
 [-1.1534941]
 [-1.0526291]
 [-0.9654015]
 [-1.2137579]
 [-0.9506321]]
2 Cost:  2.296331 
Prediction:
 [[-0.90891165]
 [-0.7281055 ]
 [-0.9415298 ]
 [-1.1534457 ]
 [-1.0525724 ]
 [-0.96534663]
 [-1.2137203 ]
 [-0.9505953 ]]
3 Cost:  2.2961595 
Prediction:
 [[-0.9088359 ]
 [-0.72803223]
 [-0.9414683 ]
 [-1.1533974 ]
 [-1.0525156 ]
 [-0.96529186]
 [-1.2136828 ]
 [-0.9505585 ]]
4 Cost:  2.295988 
Prediction:
 [[-0.90876025]
 [-0.7279588 ]
 [-0.94140667]
 [-1.1533492 ]
 [-1.0524589 ]
 [-0.965237  ]
 [-1.2136452 ]
 [-0.95052165]]
5 Cost:  2.2958164 
Prediction:
 [[-0.9086846 ]
 [-0.7278855 ]
 [-0.94134516]
 [-1.153301  ]
 [-1.0524021 ]
 [-0.9651821 ]
 [-1.2136077 ]
 [-0.9504848 ]]
6 Cost:  2.295645 
Prediction:
 [[-0.90860885]
 [-0.7278122 ]
 [-0.9412836 ]
 [-1.1532